<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>QueryRadar.Cli</RootNamespace>
    <AssemblyName>queryradar</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QueryRadar.Engine\QueryRadar.Engine.csproj" />
  </ItemGroup>

</Project>
